### PR TITLE
deprecate selendroid

### PR DESCRIPTION
**Pull request by saikrishna321**
## Change list

Deprecated Selendroid
  
http://appium.io/docs/en/drivers/android-selendroid/
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [X] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I'd also add `@deprecated` mention to the docstring containing an explanation what to use instead

**Comment by saikrishna321** [comment]
@mykola-mokhnach something like this

```
/**
 * Used to build a complex selendroid locator.
 * @deprecated Use {@link AndroidBy}
 */
@Deprecated
public @interface SelendroidBy {
```

**Comment by mykola-mokhnach** [comment]
Please address linter issues

**Comment by saikrishna321** [comment]
I can't find way to fix the linter issue '>=' i'm going to just do greater and equal

**Comment by mykola-mokhnach** [comment]
replace it with `&gt;=`

**Pull request merged**
