### PR TITLE
"getDeviceTime" function implementation

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
#296 @TikhomirovSergey @imurchie @Jonahss please review

### CODE REVIEW

**Comment by imurchie** [comment]
I think there needs to be some mapping between `GET_DEVICE_TIME` and the endpoint on the server.

https://github.com/appium/java-client/blob/cfef7a24cb122c88d5bac9d66d41f773756123a0/src/main/java/io/appium/java_client/AppiumDriver.java#L723

**Comment by SrinivasanTarget** [comment]
Yup, Thanks @imurchie

**Comment by TikhomirovSergey** [comment]
:+1: 
@Jonahss ?

**Comment by SrinivasanTarget** [comment]
@jonahss ping

**Comment by SrinivasanTarget** [comment]
@Jonahss Can this be merged?

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget 
I think it will be berged. But could you provide some tests?

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey Updated test now. please review

**Comment by TikhomirovSergey** [comment]
There is a blocker
#305 
I'm working on this one. You PR and the fix of this bug will be merged at the same time

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget I've merged your changes. 
But please be carefull further. There was a bug which I fixed on my own

**Comment by SrinivasanTarget** [comment]
Thanks @TikhomirovSergey

**Pull request merged**
