### PR TITLE
chore: patch AutomationName with Chromium

### PR DESCRIPTION
**Pull request by AlessandroMiccoli**
## Change list

Patch AutomationName with Chromium variable.
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

For running the Chromium driver, we need to set the automation name to Chromium. So, I added this variable to the interface.

### CODE REVIEW

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
@AlessandroMiccoli could you please sign the CLA?

**Comment by AlessandroMiccoli** [comment]
I already signed the CLA. I received an email. Do I need to do something else?

Screenshot 2023-08-31 at 14 17 34

**Comment by AlessandroMiccoli** [comment]
I fixed the issue with the CLA.

**Review by SrinivasanTarget — APPROVED** [review]

**Pull request merged**
