### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
@TikhomirovSergey @Jonahss Please review

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget
I won't merge this update right now because this info about the last official release. I'll update this when a new build will have been published.

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey Updated the dependencies again.

**Comment by TikhomirovSergey** [comment]
Ok. I can merge this PR. But
Please revert thes strings 
https://github.com/appium/java-client/pull/309/files#diff-04c6e90faac2675aa89e2176d2eec7d8L14
https://github.com/appium/java-client/pull/309/files#diff-04c6e90faac2675aa89e2176d2eec7d8L18

I will update this information when the new build will be published.

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey Reverted the strings.

**Pull request merged**
