### PR TITLE
#549 FIX

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
## Change list

- ByChained was re-implemented. Now it fairly searches for a single element when it is required
- AppiumElementLocator refactoring
- new tests were provided

## Types of changes
- [ ] No changes in production code.
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details
#549 FIX

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
@saikrishna321 Could you review this PR too? Also it would be cool if you built the jar using these changes and tried to **reproduce the issue**/**confirm that it is resolved**  on your app?

**Comment by SrinivasanTarget** [comment]
@saikrishna321 You can exclude it  ```./gradlew clean build -x test -x signArchives```

**Comment by saikrishna321** [comment]
@TikhomirovSergey still the issue exists. Please find the logs 

https://gist.github.com/saikrishna321/b66af4ac3659a9e4b0300db959c7e2af

its calling elements again https://gist.github.com/saikrishna321/b66af4ac3659a9e4b0300db959c7e2af#file-pr_fix-L467

**Comment by TikhomirovSergey** [comment]
@saikrishna321 
Yes. I have got it fixed now. There is my last server output
https://gist.github.com/TikhomirovSergey/3306fb9ef7e4c544a34a67a142782674

Please build and try it again on your app. I am waiting for your response.

**Comment by saikrishna321** [comment]
@TikhomirovSergey sure trying now ..

**Comment by saikrishna321** [comment]
@TikhomirovSergey Thanks it is working fine now :)

**Comment by TikhomirovSergey** [comment]
@saikrishna321 Ok. I'm going to publish 5.0.0-BETA2 soon. For now you can use the built shapshot instead.

**Pull request merged**
