### PR TITLE
Add a possibility to set pressure value for iOS

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Change list

Based on https://github.com/appium/WebDriverAgent/pull/79
 
## Types of changes

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

This will allow to automate 3D Touch/Force touch scenarios for iOS

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach Code Looks good. Can you add a test please?

**Comment by mykola-mokhnach** [comment]
Yep I can, however it won't work until the corresponding PR is merged and published

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach Is it possible to perform 3D touch using this?

**Comment by mykola-mokhnach** [comment]
it should be

**Comment by SrinivasanTarget** [comment]
Ok will try it

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget Waiting for your approval. Would be cool to include it to 6.0.0

**Pull request merged**
