### PR TITLE
#264 fix

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
Change list:
- an abilty to use few output streams during a server session was added

```java
service.addOutPutStream(stream);
```

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
@Jonahss @bootstraponline please take a look at this

**Comment by TikhomirovSergey** [comment]
#264

**Comment by smartinovic** [comment]
@TikhomirovSergey Could you also add method: setOutPutStream(stream) that will reset ListOutputStream() and add that stream:
```java
public void setOutPutStream(OutputStream outputStream){
        checkNotNull(outputStream);
        stream = new ListOutputStream().add(outputStream);
}
```

It is valuable if I don't want for stream to be outputted in System.err, and you can use it on line 47:
```java
private final ListOutputStream stream = setOutPutStream(System.err);
```

**Comment by TikhomirovSergey** [comment]
@smartinovic 
It means that by default it will print server output to console. When you'll add some another outputs when information will go to console and to another ...files, pipelines and so on. 

I think that majority of users want to see output on console at all cases. What if I'll:
- replace System.err by System.out 
- add some new methods

```java
service.addOutPutStreams(List<OutputStream> streams); 
```

?

**Comment by smartinovic** [comment]
Sounds good, it will do the trick for me.

**Comment by TikhomirovSergey** [comment]
Additional changes:
- System.err was replaced by System.out
- The additional method addOutPutStreams(List<OutputStream> outputStreams)

**Comment by bootstraponline** [comment]
Looks reasonable. :+1:

**Comment by TikhomirovSergey** [comment]
So I'm merging it

**Pull request merged**
