### PR TITLE
Partial reversion of changes related to TouchActions/MultitouchActions

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
## Change list

- flacky gesture methos stay deprecated
- removal of new classes and interfaces
- Android/iOS touch tests
- code cleaning up.
 
## Types of changes

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
ping @SrinivasanTarget

**Comment by TikhomirovSergey** [comment]
ping @SrinivasanTarget

**Comment by saikrishna321** [comment]
@TikhomirovSergey  do you think we need to add vertical swipe tests, as we are deprecating and moving towards TouchActions, i think we need to provide more examples.

Thoughts ? @SrinivasanTarget

**Comment by SrinivasanTarget** [comment]
@saikrishna321 Yes it is in plan. We will be adding more tests soon.

**Comment by TikhomirovSergey** [comment]
@saikrishna321 Vertical swiping tests are not stable as they were. I have an idea related to touch actions and I could add vertical swiping test for this feature ;)

**Pull request merged**
