### PR TITLE
Add possibility to calculate screenshots overlap score + several helpers

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Change list

This feature has been asked by several users, so I've just nicely decorated the code we use in our own automation framework and added it to the client.
 
## Types of changes

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

Screenshots comparison algorithm itself is based on standard opencv calls. That is why the library has been added to Gradle config as a dependency.

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@TikhomirovSergey is checkstyle configured properly here?

The tool does not like how one decorates loops with post-condition:
```java
        do {
....
        } while (System.currentTimeMillis() - started <= timeoutMs);
```

The output is

```
[ant:checkstyle] [ERROR] /home/travis/build/appium/java-client/src/main/java/io/appium/java_client/ScreenshotState.java:165:9: '}' at column 9 should be alone on a line. [RightCurly]
```

Somebody should be wrong here...

**Comment by SrinivasanTarget** [comment]
> The tool does not like how one decorates loops with post-condition:

We follow Google's standards :)

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach Can you rebase this branch as well with master to make commits clean?

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget squashing done. Waiting for review comments.

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget @saikrishna321 could you please find some time to finish the review?

**Comment by SrinivasanTarget** [comment]
Will review it soon

**Comment by TikhomirovSergey** [comment]
@mykola-mokhnach I remember about this PR. It is the next for the revieving.

**Comment by TikhomirovSergey** [comment]
@mykola-mokhnach 
Also there is the question. I think the scope of this feature is more general than mobile automation. Why is it necessary to include it to appium java client?

**Comment by mykola-mokhnach** [comment]
Hi @TikhomirovSergey 
It was failing because of inconsistent opencv lib import. This was one of cases when it "works for me". Now the problem should be fixed and all the unit tests were double checked as well.

**Comment by mykola-mokhnach** [comment]
Regarding why it is necessary for java lib - several users were asking for it. And we also have similar implementation in our own automation framework. So I just wanted to share verified solution and give people possibility to solve more problems with Appium (since the java client is the most popular one).

**Comment by TikhomirovSergey** [comment]
@mykola-mokhnach 
ok
Yeah. All tests are green now.

**Pull request merged**
