### PR TITLE
enable nativeWebTap setting for iOS

### PR DESCRIPTION
**Pull request by jlipps**
## Change list

add a setting for iOS to toggle `nativeWebTap`
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

Server-side change: https://github.com/appium/appium-xcuitest-driver/pull/455

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
@jlipps Looks good overall. Can you add some tests please?

**Comment by jlipps** [comment]
@SrinivasanTarget added tests, and ran it locally with success. note that this will probably fail CI since it is set to iOS 10.2 and requires appium 1.6.6-beta.2 with a fresh download. not sure what the appium local service runs in the java client... but anyway it works!

**Comment by jlipps** [comment]
found the javadoc error that was failing travis. hopefully it will pass now.

**Comment by SrinivasanTarget** [comment]
> probably fail CI since it is set to iOS 10.2 and requires appium 1.6.6-beta.2 with a fresh download

We have excluded running tests in CI, so it wouldn't be a problem now. Also this is in pipeline for us.

>not sure what the appium local service runs in the java client

Appium local service runs appium as a service automatically at stated port,etc  without being started manually.

**Comment by jlipps** [comment]
Great! Now how do we publish a beta so someone can use it? :-)

**Pull request merged**
