### PR TITLE
Fix #203

### LINKED ISSUE #203: Setting implicit wait timeout when using PageFactory
The following:
driver.manage().timeouts().implicitlyWait(0);

Doesn't affect the implicit wait - i still have to wait the time specified in Page Factory.

And the following: 
PageFactory.initElements(new AppiumFieldDecorator(driver, 0, TimeUnit.SECONDS), this);

Doesn't work - my app is still waiting the originally set timeout before confirming that the element has not been found. The original set timeout was 10 seconds and this is what I see in logs:

info: [debug] Set Android implicit wait to 10000ms

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
Change list:

- The new annotation __WithTimeout__ has been added. It provides the ability to define element rendering timeout when it differs from general values. For example some elements appear slower or some elements are used just for checkings/assertions.

Use case:

```java
@AndroidFindBy("locator")
MobileElement e1; //test will wait for this element during default time

@WithTimeout(timeOut = 20, timeUnit = TimeUnit.SECONDS)
@AndroidFindBy("locator2")
MobileElement e2; //test will wait for this diring 20 seconds

```

- AppiumFieldDecorator has been bit redesigned. Now it only decorates WebElement/MobileElement fields. 

Use case:

```java
PageFactory.initElements(new AppiumFieldDecorator(driver), 
pageObject //an instance of PageObject.class
);

//or 

PageFactory.initElements(new AppiumFieldDecorator(driver, 
          15, //default implicit waiting timeout for all strategies
        TimeUnit.SECONDS), 
            pageObject //an instance of PageObject.class
);
```

If it is extramally needed to change default time for the waiting of elements the following is possible:

```java
timeOutDuration = new TimeOutDuration(10, TimeUnit.SECONDS);  
PageFactory.initElements(new AppiumFieldDecorator(driver, timeOutDuration), pageObject);  
//user code
//here timeout has to be changed
timeOutDuration.setTime(15, TimeUnit.SECONDS); 
```

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
After the coversation with @Simon-Kaz I'm going to improve the new annotation
```java
@WithTimeout(time = 20, unit = TimeUnit.SECONDS)
```

**Comment by Jonahss** [comment]
oh I *like* this. Definitely makes it easier to define tests. Will merge when @TikhomirovSergey and @Simon-Kaz gives thumbs-up

**Comment by TikhomirovSergey** [comment]
I've finished
:+1:  :)

**Comment by Simon-Kaz** [comment]
:+1: Going to use this a lot :)

**Comment by Jonahss** [comment]
super.

**Comment by truebit** [comment]
I used `timeOutDuration.setTime(10, TimeUnit.SECONDS); ` to change global timeout in a driver wrapper class, but according to the debug log, the element find timeout is always 0:

What I did in the driver wrapper class is like below. `timeOutDuration` is a field in wrapper class. PageObject would create constructor with the wrapper class, so PageObject could use it.

```java
   public void setTimeOut(long implicitlyWaitTimeOut, TimeUnit timeUnit) {
        timeOutDuration.setTime(implicitlyWaitTimeOut, timeUnit);
        getDriver().manage().timeouts().implicitlyWait(timeOutDuration.getTime(), timeOutDuration.getTimeUnit());
        getDriver().manage().timeouts().pageLoadTimeout(timeOutDuration.getTime(), timeOutDuration.getTimeUnit());
    }
```
here below is the log when trying to finding an element for accessibility named "我的"
> [HTTP] --> POST /wd/hub/session/ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c/timeouts {"type":"implicit","ms":0}
> [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",0,"ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c"]
> [debug] [iOS] Executing iOS command 'timeouts'
> [MJSONWP] Responding to client with driver.timeouts() result: null
> [HTTP] <-- POST /wd/hub/session/ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c/timeouts 200 2 ms - 76 
> [HTTP] --> GET /wd/hub/session/ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c/context {}
> [MJSONWP] Calling AppiumDriver.getCurrentContext() with args: ["ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c"]
> [debug] [iOS] Executing iOS command 'getCurrentContext'
> [MJSONWP] Responding to client with driver.getCurrentContext() result: "NATIVE_APP"
> [HTTP] <-- GET /wd/hub/session/ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c/context 200 3 ms - 84 
> [HTTP] --> POST /wd/hub/session/ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c/elements {"using":"accessibility id","value":"我的"}
> [MJSONWP] Calling AppiumDriver.findElements() with args: ["accessibility id","我的","ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c"]
> [debug] [iOS] Executing iOS command 'findElements'
> [debug] [BaseDriver] Waiting up to 0 ms for condition
> [debug] [UIAuto] Sending command to instruments: au.getElementsByAccessibilityId('我的')
> [debug] [Instruments] [INST] 2016-04-26 10:47:26 +0000 Debug: Got new command 5 from instruments: au.getElementsByAccessibilityId('我的')
> [debug] [Instruments] [INST] 2016-04-26 10:47:26 +0000 Debug: evaluating au.getElementsByAccessibilityId('我的')
> [debug] [Instruments] [INST] 2016-04-26 10:47:27 +0000 Debug: evaluation finished
> [debug] [Instruments] [INST] 2016-04-26 10:47:27 +0000 Debug: Lookup returned [object UIAButton] with the name "我的" (id: 1).
> [debug] [Instruments] [INST] 2016-04-26 10:47:27 +0000 Debug: responding with:
> [debug] [Instruments] [INST] 2016-04-26 10:47:27 +0000 Debug: Running system command #6: /usr/local/Cellar/node/5.9.1/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-ios-driver/node_modules/appium-uiauto/build/lib/bin/command-proxy-client.js /var/folders/tf/ltnjwy0j0sn_1m58yhbm1j0h0000gn/T/instruments_sock 2,{"status":0,"value":[{"ELEMENT":"1"}]}...
> [debug] [UIAuto] Socket data received (40 bytes)
> [debug] [UIAuto] Got result from instruments: {"status":0,"value":[{"ELEMENT":"1"}]}
> [MJSONWP] Responding to client with driver.findElements() result: [{"ELEMENT":"1"}]
> [HTTP] <-- POST /wd/hub/session/ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c/elements 200 1741 ms - 89 
> [HTTP] --> POST /wd/hub/session/ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c/timeouts {"type":"implicit","ms":10000}
> [MJSONWP] Calling AppiumDriver.timeouts() with args: ["implicit",10000,"ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c"]
> [debug] [iOS] Executing iOS command 'timeouts'
> [MJSONWP] Responding to client with driver.timeouts() result: null
> [HTTP] <-- POST /wd/hub/session/ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c/timeouts 200 2 ms - 76 
> 2016-四月-26 18:47:27,608 [AppiumCabbie.java 58] INFO  - press on element : [[IOSDriver:  on MAC (ad1b6bb5-d17f-4ee3-be3d-3829cd4b6a2c)] -> accessibility id: 我的] [main]

Could you tell me what is the correct way doing global wait timeout for all PageObjects?

**Pull request merged**
