### PR TITLE
Fix end point for longPressKeyCode and fix method implementation

### PR DESCRIPTION
**Pull request by kirillbilchenko**
@TikhomirovSergey @imurchie @Jonahss please review it's minor fix, but in current version long press work incorrect.

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
There is a blocker
#305 
I'm working on this one. You PR and the fix of this bug will be merged at the same time

**Comment by kirillbilchenko** [comment]
@TikhomirovSergey please review if it's possible

**Comment by TikhomirovSergey** [comment]
@kirillbilchenko 
I'm going to check it soon and merge if everything is ok. There were problems with higher priority.

**Comment by TikhomirovSergey** [comment]
Checked and merged successfully.

**Pull request merged**
