### PR TITLE
Scrolling methods became deprecated

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
## Change list

Scrolling methods became deprecated and they are going to be removed further.
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

- The ScrollsTo interface was marked deprecated and it is going to be removed in the next release
I think it has no reasons to support them anymore. It is recommended to use instead:
 - _io.appium.java_client.AppiumDriver#swipe(int, int, int, int, int)_
 - _io.appium.java_client.MobileElement#swipe(SwipeElementDirection, int)_
 - _io.appium.java_client.MobileElement#swipe(SwipeElementDirection, int, int, int)_
 - _io.appium.java_client.MobileBy.ByAndroidUIAutomator_  or _io.appium.java_client.MobileBy.ByIosUIAutomation_

- The refactoring of **MobileBy**. This doesn't affect user's project.
 - all copied&pasted code was removed/wrapped inside methods and constructors
 - now everything looks systemically and not raw.

- The redesign of Android tests
 - ScrollTest was removed
 - tests which check scrolling locators were added to AndroidElementTest and AndroidSearchingTest

- The redesign of iOS tests
 - IOSScrollTest was removed
 - IOSScrollingSearchingTest was added instead

#366 #342 #341 #197 #226 #190 and some other related things

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget please review this

@bootstraponline Could you please take a look at this PR too?

**Comment by SrinivasanTarget** [comment]
I like this PR :) 

Changes Looks good to me except a style fix i.e line break at,
https://github.com/TikhomirovSergey/java-client/blob/scrooll_deprecated/src/main/java/io/appium/java_client/ios/IOSElement.java#L25 & https://github.com/TikhomirovSergey/java-client/blob/scrooll_deprecated/src/test/java/io/appium/java_client/android/AndroidElementTest.java#L25

Shall we close https://github.com/appium/java-client/pull/366 in favour of https://github.com/appium/java-client/pull/385?

**Comment by TikhomirovSergey** [comment]
>hall we close #366 in favour of #385?
@SrinivasanTarget 
Yes. After the merging of this PR.

**Comment by bootstraponline** [comment]
👍

**Pull request merged**
