### PR TITLE
Moving cglib dependency to an older version before 3.2.6 to resolve i…

### PR DESCRIPTION
**Pull request by canaangifford**
Referencing https://github.com/appium/java-client/issues/1100

## Change list

Moving cglib dependency to a previous version to resolve issue with the Enhancer class.
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] No changes in production code.
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by canaangifford** [comment]
See details in the bug discussion:
https://github.com/appium/java-client/issues/1100#issuecomment-501813322

I'm not sure why this cglib version is being used by appium, more insight into why would be wonderful, thanks!

**Comment by mykola-mokhnach** [comment]
@valfirst Are you ok with this change?

**Comment by valfirst** [comment]
downgrading `cglib` may make `java-client` incompatible with newer Java versions, I would propose to perform deep investigation and find out actual reason (in case of `cglib` or dependent library bug downgrade could be reasonable, otherwise I would postpone blind downgrade)

**Comment by valfirst** [comment]
@mykola-mokhnach I've investigated the issue a bit, it seems it's not caused by version upgrade: https://github.com/appium/java-client/issues/1100#issuecomment-505208545

**Pull request closed without merging**
