### PR TITLE
maven surefire to run unit tests

### PR DESCRIPTION
**Pull request by GiannisPapadakis**
1. Surefire plugin added to run unit tests on integration-test phase
2. ReentrantLock used in AppiumDriverLocalService

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
Hi @GiannisPapadakis 
I like the new maven configuration :+1: 

Please provide more details about the reason why you use the lock instead of synchronized methods.

**Comment by GiannisPapadakis** [comment]
I think a ReentrantLock is unstructured, unlike synchronized constructs for we don't need to use a block structure for locking and can even hold a lock across methods. Furthermore ReentrantLock  is more scalable (in heavy load of ThreadPoolExecutor it performs better).

**Comment by TikhomirovSergey** [comment]
Ok. I have nothing abainst change like that.

There is a minor issue. Please provide the locking here:
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/service/local/AppiumDriverLocalService.java#L75

And everything will be completed :)

**Comment by GiannisPapadakis** [comment]
Done!!!

**Comment by TikhomirovSergey** [comment]
Ok. Today I'm going to check and merge this. Thanks!

**Comment by Jonahss** [comment]
Awesome.

**Pull request merged**
