### PR TITLE
Generic AppiumDriver #178 #162 fix 

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
The major change:
- The ability to define the desired returned WebElement type has been provided:

```java
AppiumDriver<MobileElement> driver;
//some actions

MobileElement e = driver.findElement(By.id("id"));
List<MobileElement> l = driver.findElements(By.id("id"));
```

AppiumDriver is generic now and by default its finders return WebElement (it is for backward compatibility)

Possible drawbacks and backward compatibility issues:

- the necessity to perform casting to MobileElement is still here when there is long chain of the searching. But it is not so frequent.
```java
MobileElement e  = driver.findElement(By.id("id"));
MobileElement<MobileElement> e2  = (MobileElement<MobileElement>) e.findElement(By.id("id2"));
MobileElement e3 = e2.findElement(By.id("id3"));
```

- for Eclipse users.
"Rawtype" warnings. This issue is resolved by the infering of a type that implements/extends WebElement or via the suppressing of warnings like that 

```java
@SuppressWarnings("rawtypes")
someClassOrFieldOfMethod
```

- for contributors.
This solution requires IDEA (Community Edition is enough) that supports Eclipse compiler. It is compatible with Eclipse Luna or higher. It is better to use Maven v3.2.5 (I'm not sure. It is possible that minimal required version is lower. Actually I just use this version.) or higher when there is necessity to perform the local building.   

The built *.jar is copmatible wits both IDEs (Eclipse can be older than Luna) without special settings:

IDEA

idea

Eclipse

eclipse

Additional changes

- declared capabilities of MobileDriver interface have been extended
- test actualization

@Jonahss @bootstraponline 
Please review this carefully. There is no need to hurry :) If these changes will be accepted I think that next version number should be 3.0

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
#178 #162

**Comment by TikhomirovSergey** [comment]
It would be cool to resolve the issue 147 before the new release...

**Comment by bootstraponline** [comment]
I'll rely on @Jonahss for a detailed review. I'm not sure that the test code is any cleaner as a result of this. I see `<?>` everywhere. It'd be great if some users of the java-client were willing to comment since this is a large change.

**Comment by TikhomirovSergey** [comment]
Ok @bootstraponline 
Actually  <?> is not necessary. It is just only for demonstration that AppiumDriver and MobileElement are parameterized. 
With <?>  as well as without it both AppiumDriver and MobileElement work as usual

```java
WebElement e  = driver.findElement(By.id("id"));
List<WebElement> e2  = e.findElements(By.id("id2"));
```
I can improve test code if it is really needed. I think it is better to replace <?> by <WebElement>.

**Comment by Jonahss** [comment]
I'm still concerned with the need to do casting on the "chains" of finding. It's unpredictable to have to cast in that case, whereas always casting is annoying but predictable.

**Comment by TikhomirovSergey** [comment]
>I'm still concerned with the need to do casting on the "chains" of finding

Ok. then I will think about the way to improve this...

**Comment by TikhomirovSergey** [comment]
It seems that I have found the acceptable solution:

- drivers (AppiumDriver, AndroidDriver, IOSDriver) are staing generic. 

- elements (MobileElemenent, AndroidElement, IOSElement) are not generic. But their __findElement*__ and __findElements*__ methods return MobileElement or list of MobileElement.

So by default users will work as usual:

```java
AppiumDriver<?> driver;
//some actions

WebElement e = driver.findElement(By.id("id"));
List<WebElement> l = driver.findElements(By.id("id"));
```
or 

```java
AppiumDriver<WebElement> driver;
//some actions

WebElement e = driver.findElement(By.id("id"));
List<WebElement> l = driver.findElements(By.id("id"));
```

But user can choose the desired type. WebElement, TouchableElement, RemoteWebElement, MobileElement or subclasses are allowed. So when they will choose something that differs from WebElement then:

```java
AppiumDriver<MobileElement> driver;
//some actions

MobileElement e = driver.findElement(By.id("id"));
List<MobileElement> l = driver.findElements(By.id("id"));

MobileElement e1. = e.findElement(By.id("id2"));
List<MobileElement> l = e.findElements(By.id("id2"));
```
 
Everything is ready for commit. @Jonahss What do think about this? Is it ok?

**Comment by Jonahss** [comment]
Ooh yeah I like that ^.^
I'll review the code changes here and I'll update some of the examples in sample-code and such, to get a feel for it myself.

**Comment by bootstraponline** [comment]
I like the changes :+1:

**Comment by TikhomirovSergey** [comment]
@Jonahss 
I have commited improvements. Now you can check it.

When you will check this please change Java compiler to "Eclipse" if you use IDEA or download Eclipse Luna if you are Eclipse user. I advice you to perform these (for the checking):

- to build snapshot and install it to your own local maven repo. It will be better if you will perform it from command line.

- to create a small project that should depend on your local snapshot. Here you can copy/past tests or any test code you want. After please try to run tests. IDEA Java compiler can be "Javac"/ Eclipse can be Kepler or anything you want. 

Actually I did the same and everything  were cool. But you can do it to be sure that all is fine. Please let me know if something is wrong. 

This is one of the most uncommon tasks I've ever tried to resolve :)

**Comment by Jonahss** [comment]
Haha yeah it's definitely a doozy of a Java task ;)
I'm glad the setup is still easy for our users. Only complicated for
developers on the java-client.

Someday I still think it could be nice to start fresh.

**Comment by TikhomirovSergey** [comment]
Soon I will provide one commit... It is about pom.xml settings

**Comment by TikhomirovSergey** [comment]
I've improved pom.xml. So let's have fun :))

**Comment by TikhomirovSergey** [comment]
Yeah! Required changes are on Selenium side now. [(on behalf of Sergey Tikhomirov) Refactored PageFactory implementation, including a number of changes to make it more extensible and more robust....](https://raw.githubusercontent.com/SeleniumHQ/selenium/master/dotnet/CHANGELOG) I am going to propose a PR on this week or the beginning of the next!

**Comment by Jonahss** [comment]
Oh super awesome.
Sorry I've been so busy that I haven't looked closely at this yet. When you
submit the PR you are looking for, I should hopefully just merge it :)

**Comment by TikhomirovSergey** [comment]
Sorry. I have made a mistake. Another ticked has to be commented with my previous reply :))))

**Comment by Jonahss** [comment]
Oops, yeah I see it.

**Comment by RohitBandi** [comment]
Hi All,

Can you guys help me with dot net code samples after this change with generics for AppiumDriver. I Stuck and dont know how to proceed further.

Thanks

**Comment by Jonahss** [comment]
Could you post your issue to the dot net client repository then? this is
for java client :)

**Comment by fayizkc** [comment]
is it possible to create driver object with WebDriver,
I am using the framework common for both web and mobile web, So if declare  driver as AppiumDriver<WebElement> driver; it is not working for selenium web app. I feel this change is not good. Is it possible continue the old style itself (WebDriver) with latest Appium library.

**Pull request merged**
