### PR TITLE
Update applications management endpoints

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Change list

This updates application management endpoints according to the recent changes in Android and xcuitest drivers
 
## Types of changes

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach nice :boom: :star2:

**Comment by mykola-mokhnach** [comment]
Added integration tests

**Comment by mykola-mokhnach** [comment]
There are no special options for iOS for now, but the API has a possibility to add them.

> I think it has sense to move Android-specific classes to the io.appium.java_client.android packege. The same is for iOS.

np, will do.

> I can't get the test passing

I see the problem now. Will add the necessary changes to the server code. I was testing it with my local server code a while ago %)

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget https://github.com/appium/appium-uiautomator2-driver/pull/141 should be published first. Try xcuitest driver instead.

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach Its same for iOS as well. Isn't it published yet for iOS too?

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget yes,, I've just tested it on the recent beta build

**Comment by mykola-mokhnach** [comment]
Although, I had to update some iOS capabilities:

```java
        File app = new File("UICatalog-iphonesimulator.app");
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(MobileCapabilityType.BROWSER_NAME, "");
        capabilities.setCapability(MobileCapabilityType.PLATFORM_VERSION, "11.2");
        capabilities.setCapability(MobileCapabilityType.DEVICE_NAME, "iPhone 6s");
        //sometimes environment has performance problems
        capabilities.setCapability(IOSMobileCapabilityType.LAUNCH_TIMEOUT, 500000);
        capabilities.setCapability(MobileCapabilityType.APP, app.getAbsolutePath());
        driver = new IOSDriver<>(service.getUrl(), capabilities);
```

**Pull request merged**
