### PR TITLE
#242 fix

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
## Change list

- new dependencies on `org.springframework spring-context v4.3.1.RELEASE` and `org.aspectj aspectjweaver v1.8.9`

- the implemented feature

- tests

- the WIKI chapter. Please read it: https://github.com/TikhomirovSergey/java-client/blob/%23242-fix/docs/The-event_firing.md
 
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

Motivation: 

Is described at #242
Also there is no really new and interesting features since v3.1.0/v3.2.0

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget @bootstraponline could you review this PR?

@GiannisPapadakis @Simon-Kaz you are free to join the discussion :)

There is a PR proposed to Selenium: https://github.com/SeleniumHQ/selenium/pull/1034.

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey I like this PR 👍 esp. WIKI. Will review my best soon :)

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey Its nice to see @codacy-bot working in PR's.

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget  That cool. will code of tests soon.

**Comment by vikramvi** [comment]
Is there a way to configure codacy-bot to stop complaining about particular kind of issue like in this PR ?

**Comment by saikrishna321** [comment]
@vikramvi why do anyone want to do that? This helps in quick code review and code quality right..

**Comment by TikhomirovSergey** [comment]
> why do anyone want to do that? This helps in quick code review and code quality right.
Right

@vikramvi  @saikrishna321 I'm and @SrinivasanTarget for clean code. I think is good. Soon we will use CI for the PR validation and it will complain about bugs or test errors. I think it is offtop.

What do you think about the proposed PR?

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey Awesome Codacy is Green now 👍

**Comment by saikrishna321** [comment]
@TikhomirovSergey Wow .. this is real kool feature and would help a lot in reporting.

Thanks @TikhomirovSergey for working on this.

**Pull request merged**
