### PR TITLE
Upgraded Selenium version to alpha 2.

### PR DESCRIPTION
**Pull request by WasiqB**
## Change list

Bumped Selenium WebDriver version from 4.0 alpha 1 to alpha 2.
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

- Version upgraded.
- Added `Duration` to `WebDriverWait`.

### CODE REVIEW

**Comment by WasiqB** [comment]
@SrinivasanTarget , will update by tomorrow.

**Comment by mykola-mokhnach** [comment]
@saikrishna321 Does this mean we are not going to publish any stable java client versions anymore until selenium4 is released?

**Comment by saikrishna321** [comment]
@mykola-mokhnach Thought was to release beta versions v7.3.0-beta1

**Comment by mykola-mokhnach** [comment]
yes, although we will still have to wait for stable selenium version in order to release a new stable appium client version (let say 7.3.0). Do we want it?

**Comment by SrinivasanTarget** [comment]
We can release a beta till then. AFAIK Simon will be releasing the stable version very soon as most of the client-side planned work was done but I'm not aware of the date though.

**Pull request merged**
