### PR TITLE
Fix for issue #208 and #219

### PR DESCRIPTION
**Pull request by aniket-21**

### CODE REVIEW

**Comment by bgordon-applause** [comment]
Would it be possible for someone to review this, and get it merged?  Thanks!

**Comment by TikhomirovSergey** [comment]
Hi @aniket-21 
I can't make a decision. Let's wait for @Jonahss

Now your changes are in conflict with the master. The conflicted code:https://github.com/appium/java-client/pull/233/files#diff-c60f84c0cc90f37a9a4513eeebd4896dR214

The command map filling has been moved here:
https://github.com/appium/java-client/blob/master/src/main/java/io/appium/java_client/AppiumDriver.java#L666

**Comment by aniket-21** [comment]
Yes, I can resolve the conflict. ImmutableMap builder has just been moved under the getMobileCommands()

@TikhomirovSergey let me know if you would be able to handle this during merge else I will create a new pull request

**Comment by aniket-21** [comment]
@TikhomirovSergey can you take a look now?

**Comment by TikhomirovSergey** [comment]
Yep. As for me it is ok. But the communicatin with the server and low level features is not my area.

**Comment by Jonahss** [comment]
Looks great. Those two issues have been pending for a while, thanks very much for clearing them up.

**Pull request merged**
