### PR TITLE
Google Java Style validation

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
## Change list

Checkstyle validation to ensure google java code style is followed or not
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

##Details

Continuation of https://github.com/appium/java-client/pull/346

@TikhomirovSergey @Jonahss @bootstraponline Please take a look at this PR :)

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
We can perform checks through maven going forward from CI.
https://maven.apache.org/plugins/maven-checkstyle-plugin/plugin-info.html

**Comment by SrinivasanTarget** [comment]
Great to see our repo audit reports shows there are "0" errors and "7774" warnings that we can work out.

**Comment by SrinivasanTarget** [comment]
screen shot 2016-04-07 at 12 14 07 am

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget 
I like this PR :+1: 
But I a little but modified it. My modification is here: https://github.com/TikhomirovSergey/java-client/blob/SrinivasanTarget-master/pom.xml

I'm going to merge this PR with my own modification after source code improvement.

**Comment by SrinivasanTarget** [comment]
I like your modification @TikhomirovSergey 👍

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey Added goals as per your comments :)

**Comment by SrinivasanTarget** [comment]
👍

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey Have a query. Are we expecting this (https://github.com/TikhomirovSergey/java-client/blob/f64c9a189038af7915e17bbbd829c0f7cab6d262/src/test/java/io/appium/java_client/ios/IOSDriverTest.java#L71) to fail?

**Comment by SrinivasanTarget** [comment]
Thanks for adding me:)

**Comment by bootstraponline** [comment]
> CI build should be failed on code style violation

👍

**Pull request merged**
