### PR TITLE
fix: Properly translate desiredCapabilities into a command line argument

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Types of changes

- [ ] No changes in production code.
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

Addresses https://github.com/appium/java-client/issues/1336

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget Could you please rerun the E2E tests? I've just patched the UIA2 driver

**Comment by SrinivasanTarget** [comment]
> @SrinivasanTarget Could you please rerun the E2E tests? I've just patched the UIA2 driver

Retriggered now

**Comment by root-intruder** [comment]
@mykola-mokhnach I also recently stumbled across this. With your fix, it seems that no arguments are escaped with `\"` which means that it always has to be manually escaped for every capability.

I see why a fix was needed, but that makes the situation worse for all windows users using mostly common simple capabilities such as "app" or "udid".

Is there any mechanism to work against this problem, without now quoting each arguments I pass to the capabilities.

Thanks!

**Comment by root-intruder** [comment]
@mykola-mokhnach thanks for the answer! How about overloading `public AppiumServiceBuilder withCapabilities(DesiredCapabilities capabilities)"` as `public AppiumServiceBuilder withCapabilities(DesiredCapabilities capabilities, boolean quoteAllCapabilities)`

and then quote everything in `private String capabilitiesToCmdlineArg()` https://github.com/appium/java-client/blob/bcca20276191f98d9293974b6430cb97cb5e465c/src/main/java/io/appium/java_client/service/local/AppiumServiceBuilder.java#L299 if quoteAllCapabilities is set?!

Then still the user could decide if he want's to quote everything. 

Alternatively it would also be possible to make quoting everything the default on windows systems and only disable it if the user sets the flag. This way, most win users wouldn't have to escape by hand and special cases like #1336 can still be addressed.

Cheers!

**Comment by mykola-mokhnach** [comment]
The overload proposal seems reasonable to me. Feel free to create a pull request

**Comment by root-intruder** [comment]
@mykola-mokhnach would you be fine with the described second option: quoting everything on win systems and the user needs to opt out and then manually quote in cases as described in #1336?

I'd do a pull request in the next days!

**Comment by mykola-mokhnach** [comment]
> would you be fine with the described second option: quoting everything on win systems and the user needs to opt out and then manually quote in cases as described in #1336?

I would rather stick to the first option, since changing the default behaviour is a breaking change. Clients must explicitly opt in for "automatic" quoting if they want to

**Comment by root-intruder** [comment]
you're absolutely right...didn't think of existing users

**Pull request merged**
