### PR TITLE
Added getElementScreenshot handler.

### PR DESCRIPTION
**Pull request by saikrishna321**
Co-authored-by: SrinivasanTarget <srinivasan.sekar1990@gmail.com>

## Change list

https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L581

This PR helps to get screenshot of specific MobileElement.
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I don't understand why this is needed. There is https://github.com/SeleniumHQ/selenium/blob/5f5ddb9915cd147bc841bb2ac0813f0804dd65f9/java/client/src/org/openqa/selenium/remote/RemoteWebElement.java#L384

**Comment by SrinivasanTarget** [comment]
GetScreenshotAs gets whole visible screen's screenshot but we are not sure
about the usecase behind getting screenshot of specific element.

**Comment by mykola-mokhnach** [comment]
Did you check which server API is called under the hood?

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach I see the difference [here](https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/DriverCommand.java#L92-L93) at selenium side. Ideally getScreenshotAs consumes this [endpoint](https://github.com/appium/appium-base-driver/blob/master/lib/protocol/routes.js#L80) if i'm not wrong.

**Comment by SrinivasanTarget** [comment]
Yes I'm right. https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/remote/http/AbstractHttpCommandCodec.java#L155

**Comment by SrinivasanTarget** [comment]
@jlipps Do you have know any usecase behind clicking screenshot of a particular element?

**Comment by jlipps** [comment]
i don't think it's about clicking the screenshot. i think it's about getting an image of just a particular element. you could imagine it'd be easier to verify a cropped element image than the whole view, which might change around the element.

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget no, it's this endpoint: https://github.com/SeleniumHQ/selenium/blob/0213e013f0b849506bc2c204ad72d224f0f9e75e/java/client/src/org/openqa/selenium/remote/http/AbstractHttpCommandCodec.java#L156

**Comment by SrinivasanTarget** [comment]
@mykola-mokhnach Getting unsupported command exception at selenium. May be a probable bug at selenium end to be raised there.

**Comment by saikrishna321** [comment]
@SrinivasanTarget and @mykola-mokhnach i tried it with latest BETA3 java-client and it works 👍 

```
        File slider1 = getDriver().findElementByAccessibilityId("login").getScreenshotAs(OutputType.FILE);
        FileUtils.copyFile(slider1, new File("sample.png"));
```

sample

Is there something that we can check before going ahead and creating stuff on client, like selenium already supports and appium server handles from there and clients don't need any updates ?

**Pull request closed without merging**
