### PR TITLE
#342 Fix

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
## Change list

Added ScrollToUsingPredicates method for android and iOS
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

##Details

ScrollTo  -  Existing method doesn't work for UIScrollableView.It works fine only for UITableView since it is hardcoded. This will again be re-fractored in upcoming commits in same PR.

Now introduced a new method "ScrollToUsingPredicates" for both android and iOS that enables user to define their own predicates that works fine for any scrollable views.

For Predicates in iOS refer: 
1)https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/ios_predicate.md
2)https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSPredicate_Class/

For Android Scroll refer:
1)http://developer.android.com/reference/android/support/test/uiautomator/UiScrollable.html#scrollTextIntoView(java.lang.String)

@TikhomirovSergey Your thoughts on this?

As we discussed,this PR will continue to fix existing ScrollTo method.Will work on this.

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/issues/342

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget 
I'm against the proposed PR is it is now.  It is much easier to make scrolling methods _deprecated_ and remove it later and make users to use **findBySomeAutomation** instead. May be it is more correct solution but it is not convenient I think. 

I'm looking forward for more complex solution:

- 1. There is no need to modify  io.appium.java_client.ScrollsTo. Let it stay as it is.

- 2. MobileBy needs for some refacoring I think. It would be cool if it looked like the sample below after the refactoring:

```java
...
public abstract class MobileBy extends By implements Serializable {
    private final String automatorText;

    public MobileBy(String automatorText) {
        this.automatorText = automatorText;
    }

    protected String getAutomatorText() {
        return automatorText;
    }

    ...
    
    public static class ByIosUIAutomation extends MobileBy  {
        public ByIosUIAutomation(String uiautomationText) {
            super(uiautomationText);
        }

        @SuppressWarnings("unchecked")
        @Override
        public List<WebElement> findElements(SearchContext context) {
            return (List<WebElement>) ((FindsByIosUIAutomation<?>) context)
                    .findElementsByIosUIAutomation(getAutomatorText());
        }

        @Override public WebElement findElement(SearchContext context) {
            return ((FindsByIosUIAutomation<?>) context)
                .findElementByIosUIAutomation(getAutomatorText());
        } 

        @Override public String toString() {
            return "By.IosUIAutomation: " + getAutomatorText();
        } 
    }
  
    public static class ByAndroidUIAutomator extends By implements Serializable {
        public ByAndroidUIAutomator(String uiautomatorText) {
            super(uiautomationText);
        }

        @SuppressWarnings("unchecked")
        @Override
        public List<WebElement> findElements(SearchContext context) {
            return (List<WebElement>) ((FindsByAndroidUIAutomator<?>) context)
                    .findElementsByAndroidUIAutomator(getAutomatorText());
        }

        @Override public WebElement findElement(SearchContext context) {
            return ((FindsByAndroidUIAutomator<?>) context)
                .findElementByAndroidUIAutomator(getAutomatorText());
        }

        @Override public String toString() {
            return "By.AndroidUIAutomator: " + automatorText;
        }

        @Override public String getAutomatorText() {
            return automatorText;
        }
    }

    public static class ByAccessibilityId extends By implements Serializable {

        private final String id;

        public ByAccessibilityId(String id) {
            this.id = id;
        }

        @SuppressWarnings("unchecked")
        @Override
        public List<WebElement> findElements(SearchContext context) {
            return (List<WebElement>) ((FindsByAccessibilityId<?>) context)
                .findElementsByAccessibilityId(id);
        }

        @Override public WebElement findElement(SearchContext context) {
            return ((FindsByAccessibilityId<?>) context).findElementByAccessibilityId(id);
        }

        @Override public String toString() {
            return "By.AccessibilityId: " + id;
        }
    }
}
```

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget what do you think about this solution?

@bootstraponline @Jonahss you can join to this discussion if you want.
@autoaim800 @nuggit32 you are invited too.

#341

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey Above suggested Android changes looks fine for me,

Have few queries w.r.t iOS,

1) Why are we not gonna refractor existing ScrollTo method? It works fine only for "UITableView" but not for other scrollable views e.g "UIScrollView"
2) I see above suggested iOS changes also uses "UITableView" hard coded, this serves the same way as existing ScrollTo i.e may work only for UITableView.

```
public T scrollToUsingPredicate(By scrollableElementBy, String iOSpredicate) {
        return (T) findElementBy(scrollableElementBy)
            .scrollToUsingPredicate(iOSpredicate);
   }

   public T scrollToUsingPredicate(String iOSpredicate) {
        return scrollToUsingPredicate(By.className("UIATableView"), iOSpredicate);
   }
```
I think we need to use ByIosUIAutomation instead of By. Still not clear with this portion.Please clarify.

**Comment by autoaim800** [comment]
Hi 
Thanks for inviting me.

I'm just thinking aloud:

#341 supposed to be fixed by #342, and #342 is supposed to be fixed by #366

For #341 the issue is scrollTo() and/or scrollToExact() can not be stopped at first occurrence at first glance, what's the root cause?
I thought it's not fix-able, as on Android, ListView has to scroll top->bottom to build a complete list of cells - as cells are not loaded at first/once (not like iOS), that's why only on its way back bottom->top, it stops at the first occurrence; correct me if I'm mistaken - I only have observation, no evidence at all to back up myself.

For #342, the solution seems reasonable from my perspective, either stick/correct the old-fashion implementation or introduce new method/feature works fine for me.

For #366, it's more like a new feature - can I say I like both two new methods to be added.

-Bill

**Comment by TikhomirovSergey** [comment]
https://github.com/appium/java-client/issues/197

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/issues/226

**Comment by SrinivasanTarget** [comment]
@autoaim800 Thanks for your comments. Your observations are correct and the above tagged/discussed issues will be addressed.

@TikhomirovSergey Have updated another possible iOS solution that works for all scrollable views now.Please have a look.Waiting for your comments:)

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey  

**Second Solution:**
Have altered your solution here below, please check which one would be good to have,

*MobileBy will be re-fractored as you said above
*AndroidDriver will have below changes,
```
    static String uiScrollablenew(String uiSelector) {
        return "new UiScrollable(new UiSelector().scrollable(true).instance(0))"
            + ".scrollTextIntoView(\"" + uiSelector + "\");";
    }

    public T scrollToUsingAutomator(ByAndroidUIAutomator by) {
        return findElementByAndroidUIAutomator(uiScrollablenew(by.getAutomatorText()));
    }
```
*IOSDriver will have below changes,
```
    static String scrollToVisible(ByIosUIAutomation scrollableElementBy) {
        return  scrollableElementBy.getAutomatorText() + ".scrollToVisible();";
    }

    public T scrollToUsingAutomator(ByIosUIAutomation scrollableElementBy) {
        return (T) findElementByIosUIAutomation(scrollToVisible(scrollableElementBy));
    }
```

Your thoughts on solution comitted and the second one?

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/2942

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/4633

**Comment by SrinivasanTarget** [comment]
appium/appium#4633

**Comment by TikhomirovSergey** [comment]
I'm closing it according to #385

**Pull request closed without merging**
