### PR TITLE
The refactoring and test coverage

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
Change list:
- the command forming was moved from the AppiumDriver to MobileCommand
- MobileCommand is a class now (was an interface).
- Improved test coverage. Now there are tests for both Android and iOS (some test were for iOS only)

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
@bootstraponline @imurchie 
Please review these changes.

**Comment by TikhomirovSergey** [comment]
#302

**Comment by bootstraponline** [comment]
The merge commits should be rebased out of the commit history. Code looks good.

**Comment by TikhomirovSergey** [comment]
Was improved. Now I'm merging.

**Pull request merged**
