### PR TITLE
spell-check and fixed IOSAlertTest

### PR DESCRIPTION
**Pull request by saikrishna321**
## Change list

Please provide briefly described change list which are you going to propose. 
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#Details

Fixed IOSAlertTest and Spell-check fixes.

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
@saikrishna321 Can you sign CLA? Also as discussed you can add @CacheLookup onto both Android and iOS Page factory tests to improve performance. Would be good if you update issue template and title above with all details. Will review soon.

**Comment by saikrishna321** [comment]
@SrinivasanTarget i have signed the CLA, not sure why its still showing here .. 

I see issue Duplicate Annotation error on PageFactory tests 

screen shot 2016-11-01 at 12 59 51 pm

**Comment by TikhomirovSergey** [comment]
@saikrishna321 
Yesterdey you have proofed that everything is ok. https://github.com/appium/java-client/pull/503
Have you tried to Invalidate caches and restart IDEA?

image

**Comment by saikrishna321** [comment]
Yesterday Srinivas had asked me to just run the page object tests ....

**Comment by saikrishna321** [comment]
@TikhomirovSergey worked... will add test with CachedLookUp and logs to it

**Comment by TikhomirovSergey** [comment]
@saikrishna321 
About CachedLookUp

I think it would be better to add one more test method which checks 

```java
@CachedLookUp
@FindBy(someLocator)
private MobileElement cached;
...

public void checkCached() {
  assertEquals(cached.getId(), cached.getId()); //each time when you 
//start to search for the element appium returns it with the different id
//even when locator is the same
//so you can use it for the testing of the caching
}
```

**Pull request closed without merging**
