### PR TITLE
Add endpoints for screen recording API for iOS and Android

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Change list

Add endpoints for screen recording API for iOS and Android
 
## Types of changes

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details
https://github.com/appium/appium-android-driver/pull/303
https://github.com/appium/appium-xcuitest-driver/pull/609

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
@mykola-mokhnach There is the conflict. Could you resolve it?
Will try it ASAP .

**Comment by mykola-mokhnach** [comment]
Rebased it with master

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget I would be happy to add test, but currently the client interaction with Appium beta is broken, so I cannot even init a session properly. See https://github.com/appium/appium/issues/10055 for more details.

**Comment by SrinivasanTarget** [comment]
> See appium/appium#10055 for more details.

@mykola-mokhnach  Yes just looking at it. I think we need to work on W3C support asap from your other PR.

**Comment by mykola-mokhnach** [comment]
@TikhomirovSergey @SrinivasanTarget The recent server beta has a workaround for w3c issue, so I was able to create and check integration tests for the feature.

**Pull request merged**
