### PR TITLE
chore: deprecate tapWithShortPressDuration cap

### PR DESCRIPTION
**Pull request by rerorero**
## Change list
This PR removes tapWithShortPressDuration cap.
see https://github.com/appium/appium-xcuitest-driver/pull/1481
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [x] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

see https://github.com/appium/appium-xcuitest-driver/pull/1481

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Please mark it as deprecated first. Then we remove the constant in later releases

**Comment by rerorero** [comment]
OK, marked it as deprecated.

**Comment by mykola-mokhnach** [comment]
> /Users/runner/work/java-client/java-client/src/main/java/io/appium/java_client/remote/IOSMobileCapabilityType.java:174: error: unknown tag: Deprecated
> [36](https://github.com/appium/java-client/actions/runs/3797269944/jobs/6461608860#step:4:37)
>      * @Deprecated This capability is not being used.

Are you sure the tag name has been spelled correctly?

**Comment by rerorero** [comment]
oops, sorry. fixed

**Review by valfirst — APPROVED** [review]

**Pull request merged**
