### PR TITLE
fix: Scroll issue in flutter integration driver

### PR DESCRIPTION
**Pull request by MummanaSubramanya**
## Change list

This PR address the issue https://github.com/AppiumTestDistribution/appium-flutter-integration-driver/issues/88
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] No changes in production code.
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

Please provide more details about changes if it is necessary. If there are new features you can provide code samples which show the way they
work and possible use cases. Also you can create [gists](https://gist.github.com) with pasted java code samples or put them here using markdown. 
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on GitHub](https://help.github.com/categories/writing-on-github/)

### CODE REVIEW

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
@MummanaSubramanya I can also observe one flutter integration test failing in CI env: https://github.com/appium/java-client/actions/runs/10611872941/job/29413196070?pr=2227. Could you please check if it needs to be updated together with this PR?

**Comment by MummanaSubramanya** [comment]
> @MummanaSubramanya I can also observe one flutter integration test failing in CI env: https://github.com/appium/java-client/actions/runs/10611872941/job/29413196070?pr=2227. Could you please check if it needs to be updated together with this PR?

test fixed

**Comment by jlipps** [comment]
Hi @MummanaSubramanya , congrats, the Appium project wants to compensate you for this (and perhaps other) contribution(s) this month! Please reply to this comment mentioning me and sharing your [OpenCollective](https://opencollective.com) account name, so that we can initiate payment! Or let me know if you decline to receive compensation via OpenCollective. Thank you!

**Comment by MummanaSubramanya** [comment]
> Hi @MummanaSubramanya , congrats, the Appium project wants to compensate you for this (and perhaps other) contribution(s) this month! Please reply to this comment mentioning me and sharing your [OpenCollective](https://opencollective.com) account name, so that we can initiate payment! Or let me know if you decline to receive compensation via OpenCollective. Thank you!

Hi @jlipps, thank you so much for the kind gesture and support! I gratefully accept the compensation via OpenCollective. My OpenCollective account name is `MummanaSubramanya`

I look forward to contributing even more to the Appium community!

Thanks again!

**Pull request merged**
