### PR TITLE
Predicate locator added in IOSDriver, IOSElement, and iOSFindBy

### PR DESCRIPTION
**Pull request by mt1729**
## Types of changes

Added support for the existing FindsByIosNSPredicate interface to the classes above and in PageFactory strategies. Tests for each were updated to reflect changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by mt1729** [comment]
Oops, must have snuck in there. Fixed

**Comment by SrinivasanTarget** [comment]
I don't have iOS 9 devices with me to test. @TikhomirovSergey ping

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget @mt1729 
It looks ok generally. But I need for some claryfication. 
Does it work at the common IOSDriver starting? Don't you need the specific automation type?

**Comment by mt1729** [comment]
@TikhomirovSergey I don't believe the common driver has been updated yet to support finding elements directly by predicate, so this seems to be specific to the new XCUITest driver.

However, do you think it would be reasonable to use the UI Automation [predicate helpers](https://github.com/appium/appium-uiauto/blob/3052dace828db2ab3d722281fb7853cbcbc3252f/uiauto/appium/app.js#L68) when finding by predicate using the common driver?

**Comment by SrinivasanTarget** [comment]
@mt1729 Yup Initially i was confused. Btw Are you able to get this working in XCUITest? If so can you please share your execution logs which succeed. I was not able to use this locator in XCUITest as well.

**Comment by mt1729** [comment]
@SrinivasanTarget Made a small mistake in the tests. The property should have been 'label' instead of 'name' which I've updated. [Here](https://gist.github.com/mt1729/0a09dfa11e945428c407e8d6af26ec1c) are the logs for one of the tests running on my machine.

**Comment by SrinivasanTarget** [comment]
@mt1729 Got it. But it will fail on legacy driver.This should probably get in post https://github.com/appium/java-client/issues/398

**Comment by rafael-chavez** [comment]
@SrinivasanTarget is this not the exact same thing that was removed here?
https://github.com/appium/java-client/pull/394

**Comment by rafael-chavez** [comment]
Ping @SrinivasanTarget

**Comment by SrinivasanTarget** [comment]
@rafael-chavez Yup will look into it soon. Please sign here: https://github.com/appium/java-client/pull/523

**Comment by TikhomirovSergey** [comment]
Sorry for the late responce.  I'm closing this PR in favor https://github.com/appium/java-client/pull/545

**Pull request closed without merging**
