### PR TITLE
Repeatable annotations & HasSessionDetails API

### PR DESCRIPTION
**Pull request by TikhomirovSergey**
## Change list

Migration to Java 8. Repeatable annotations for page objects:
- Annotations `AndroidFindAll`, `AndroidFindBys`, `iOSFindAll`, `iOSFindBys`, `SelendroidFindAll`, 
  `SelendroidFindBys` became deprecated.
- Annotations `AndroidFindBy`, `iOSFindBy`, `SelendroidFindBy` became repeatable. 
- The new annotation `io.appium.java_client.pagefactory.HowToUseLocators` was added to help to define the searching strategy (chain or using all possible locators) correctly.

Also were added:
- The `io.appium.java_client.HasSessionDetails` interface. It has methods implemented by default. This interface is implemented by `AppiumDriver`
- The refactoring of the `io.appium.java_client.AppiumFieldDecorator` and related supporting tools. Now it uses session data instead of the class of the given driver for the routing between annotations. 
## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Details
# 399 #454
### The old usecase for the chained searching:

``` java
import org.openqa.selenium.remote.RemoteWebElement;
import io.appium.java_client.pagefactory.*;
import org.openqa.selenium.support.FindBys;
import org.openqa.selenium.support.FindBy;

@FindBys({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBys({@AndroidFindBy(someStrategy1), @AndroidFindBy(someStrategy2)}) 
@iOSFindBys({@iOSFindBy(someStrategy1), @iOSFindBy(someStrategy2)}) 
RemoteWebElement someElement;

@FindBys({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBys({@AndroidFindBy(someStrategy1), @AndroidFindBy(someStrategy2)}) 
@iOSFindBys({@iOSFindBy(someStrategy1), @iOSFindBy(someStrategy2)}) 
List<RemoteWebElement> someElements;
```
### New usecases for the chained searching:

``` java
import org.openqa.selenium.remote.RemoteWebElement;
import io.appium.java_client.pagefactory.*;
import org.openqa.selenium.support.FindBys;
import org.openqa.selenium.support.FindBy;

@FindBys({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBy(someStrategy1) @AndroidFindBy(someStrategy2)
@iOSFindBy(someStrategy1) @iOSFindBy(someStrategy2) 
RemoteWebElement someElement;

@FindBys({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBy(someStrategy1) @AndroidFindBy(someStrategy2)
@iOSFindBy(someStrategy1) @iOSFindBy(someStrategy2)
List<RemoteWebElement> someElements;
```

or 

``` java
import org.openqa.selenium.remote.RemoteWebElement;
import io.appium.java_client.pagefactory.*;
import org.openqa.selenium.support.FindBys;
import org.openqa.selenium.support.FindBy;

import static io.appium.java_client.pagefactory.LocatorGroupStrategy.CHAIN;

@HowToUseLocators(androidAutomation = CHAIN, iOSAutomation = CHAIN)
@FindBys({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBy(someStrategy1) @AndroidFindBy(someStrategy2)
@iOSFindBy(someStrategy1) @iOSFindBy(someStrategy2) 
RemoteWebElement someElement;

@HowToUseLocators(androidAutomation = CHAIN, iOSAutomation = CHAIN)
@FindBys({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBy(someStrategy1) @AndroidFindBy(someStrategy2)
@iOSFindBy(someStrategy1) @iOSFindBy(someStrategy2)
List<RemoteWebElement> someElements;
```
### The old usecase for the searching by all possible locators:

``` java
import org.openqa.selenium.remote.RemoteWebElement;
import io.appium.java_client.pagefactory.*;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.FindByAll;

@FindAll({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindAll({@AndroidFindBy(someStrategy1), @AndroidFindBy(someStrategy2)}) 
@iOSFindAll({@iOSFindBy(someStrategy1), @iOSFindBy(someStrategy2)}) 
RemoteWebElement someElement;

@FindAll({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindAll({@AndroidFindBy(someStrategy1), @AndroidFindBy(someStrategy2)}) 
@iOSFindAll({@iOSFindBy(someStrategy1), @iOSFindBy(someStrategy2)}) 
List<RemoteWebElement> someElements;
```
### The new usecase for the searching by all possible locators:

``` java
import org.openqa.selenium.remote.RemoteWebElement;
import io.appium.java_client.pagefactory.*;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.FindByAll;

import static io.appium.java_client.pagefactory.LocatorGroupStrategy.ALL_POSSIBLE;

@HowToUseLocators(androidAutomation = ALL_POSSIBLE, iOSAutomation = ALL_POSSIBLE)
@FindAll{@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBy(someStrategy1) @AndroidFindBy(someStrategy2) 
@iOSFindBy(someStrategy1) @iOSFindBy(someStrategy2) 
RemoteWebElement someElement;

@HowToUseLocators(androidAutomation = ALL_POSSIBLE, iOSAutomation = ALL_POSSIBLE)
@FindAll({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBy(someStrategy1) @AndroidFindBy(someStrategy2)
@iOSFindBy(someStrategy1) @iOSFindBy(someStrategy2)
List<RemoteWebElement> someElements;
```
### Also possible combined variants:

``` java
import org.openqa.selenium.remote.RemoteWebElement;
import io.appium.java_client.pagefactory.*;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.FindByAll;

import static io.appium.java_client.pagefactory.LocatorGroupStrategy.CHAIN;
import static io.appium.java_client.pagefactory.LocatorGroupStrategy.ALL_POSSIBLE;

@HowToUseLocators(androidAutomation = CHAIN, iOSAutomation = ALL_POSSIBLE)
@FindAll{@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBy(someStrategy1) @AndroidFindBy(someStrategy2) 
@iOSFindBy(someStrategy1) @iOSFindBy(someStrategy2) 
RemoteWebElement someElement;

@HowToUseLocators(androidAutomation = CHAIN, iOSAutomation = ALL_POSSIBLE)
@FindAll({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBy(someStrategy1) @AndroidFindBy(someStrategy2)
@iOSFindBy(someStrategy1) @iOSFindBy(someStrategy2)
List<RemoteWebElement> someElements;
```

or 

``` java
import org.openqa.selenium.remote.RemoteWebElement;
import io.appium.java_client.pagefactory.*;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.FindByAll;

import static io.appium.java_client.pagefactory.LocatorGroupStrategy.ALL_POSSIBLE;

@HowToUseLocators(iOSAutomation = ALL_POSSIBLE)
@FindAll{@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBy(someStrategy1) @AndroidFindBy(someStrategy2) //this is the chain 
//by default
@iOSFindBy(someStrategy1) @iOSFindBy(someStrategy2) 
RemoteWebElement someElement;

@HowToUseLocators(iOSAutomation = ALL_POSSIBLE)
@FindAll({@FindBy(someStrategy1), @FindBy(someStrategy2)}) 
@AndroidFindBy(someStrategy1) @AndroidFindBy(someStrategy2) //this is the chain 
//by default
@iOSFindBy(someStrategy1) @iOSFindBy(someStrategy2)
List<RemoteWebElement> someElements;
```

### CODE REVIEW

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget could you review it? :)

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget The issue which you pointed has got fixed.

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey I like this PR. Gonna be a big change. Code LGTM 👍 Haven't run through the tests, will run through it soon.

**Comment by saikrishna321** [comment]
@TikhomirovSergey i'm finding hard to understand the use-of @HowToUseLocators(androidAutomation = CHAIN, iOSAutomation = ALL_POSSIBLE) can you please throw some light on this ?

**Comment by SrinivasanTarget** [comment]
@saikrishna321 Please find the simple use case below,

```
@HowToUseLocators(androidAutomation = CHAIN,iOSAutomation = ALL_POSSIBLE)
@AndroidFindBy(some UISelector()) @AndroidFindBy(Some view or text inside it) 
@iOSFindBy(xpath1) @iOSFindBy(xpath2)
List<RemoteWebElement> someElements;
```

It has lot more cases like this...

**Comment by saikrishna321** [comment]
@SrinivasanTarget yah i get this... but what does CHAIN and ALL_POSSIBLE do ?

**Comment by SrinivasanTarget** [comment]
@saikrishna321 Have updated the comments above. Let me know if it is not clear.

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey Have run through android tests and everything LGTM

**Comment by TikhomirovSergey** [comment]
@saikrishna321 
>yah i get this... but what does CHAIN and ALL_POSSIBLE do ?

That means that each one platform-specific locator can be a part of the chaing of the searching or it is one of possible variants to find the desired element/the desired list  of elements as well. 

Before we have been using such annotations as **@AndroidFindBys({@AndroidFindBy(1),@AndroidFindBy(2)})**/**@iOSFindBys({@iOSFindBy(1), @iOSFindBy(2)})** to define the searching chain and **@AndroidFindAll({@AndroidFindBy(1),@AndroidFindBy(2)})**/**@iOSFindAll({@iOSFindBy(1), @iOSFindBy(2)})** to define possible locators for the searching. 

Now we are migrating to Java 8. It provides reapeatable annotations: http://docs.oracle.com/javase/tutorial/java/annotations/repeating.html

So I think that some annotations above are redundant now. We could define the chain like:
**@AndroidFindBy(1) @AndroidFindBy(2)**/**@iOSFindBy(1) @iOSFindBy(2)*
But it is still possible that and user needs to find these locators as the set of possible variants to search for an element. 

So
```
@HowToUseLocators(iOSAutomation = ALL_POSSIBLE, androidAutomation = ALL_POSSIBLE)
@AndroidFindBy(1) @AndroidFindBy(2)
@iOSFindBy(1) @iOSFindBy(2)
```

If the end user needs for combined strategy for each target platform then

```
@HowToUseLocators(iOSAutomation = CHAIN, androidAutomation = ALL_POSSIBLE)
@AndroidFindBy(1) @AndroidFindBy(2) //each one locator is the 
//possible variant to find elements
@iOSFindBy(1) @iOSFindBy(2) //it is for the chained searching
```

or 

```
@HowToUseLocators(androidAutomation = ALL_POSSIBLE)
@AndroidFindBy(1) @AndroidFindBy(2) //each one locator is the 
//possible variant to find elements
@iOSFindBy(1) @iOSFindBy(2) //it is for the chained searching by default
```

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget 
How does iOS feels?

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey 
>How does iOS feels? 

Have upgraded my xcode to 8 so i cant run through existing tests on XCUTest Mode. But test code for iOS looks good to me.

**Comment by saikrishna321** [comment]
I'm still on xcode 7, any help needed to run the iOS test ?

**Comment by saikrishna321** [comment]
@TikhomirovSergey well explained, i had a chat with @SrinivasanTarget on @CacheLookup will take a look on it ..

**Comment by SrinivasanTarget** [comment]
>I'm still on xcode 7, any help needed to run the iOS test ?

@saikrishna321 May be you can help us with ```IOSPageFactoryTest```

**Comment by saikrishna321** [comment]
@TikhomirovSergey @SrinivasanTarget all tests passed( Tested on iPhone 9.3 Simulator, xcode 7) 👍

**Pull request merged**
