### PR TITLE
Remove console output from AppiumDriverLocalService by default

### PR DESCRIPTION
**Pull request by Mygod**
## Change list

Remove console output from AppiumDriverLocalService by default. 
## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
## Details

Reason: I need to use `System.out` to print some less verbose output. And user can easily turn it back on by calling `addOutPutStream`.

However the other way around is hard. Here's what I'm currently using.

```
        try {
            streamField = AppiumDriverLocalService.class.getDeclaredField("stream");
            streamField.setAccessible(true);
            streamsField = Class.forName("io.appium.java_client.service.local.ListOutputStream")
                    .getDeclaredField("streams");
            streamsField.setAccessible(true);
        } catch (ClassNotFoundException | NoSuchFieldException e) {
            e.printStackTrace();
        }
        try {
            ((ArrayList<OutputStream>) streamsField.get(streamField.get(service))).clear(); // remove System.out logging
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
```

### CODE REVIEW

**Comment by alexander-poulikakos** [comment]
I fully agree on this PR. We should not log to System.out by default.

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey ping

**Comment by jeangb** [comment]
Hi, this looks very interesting.
Any news on this ?

**Comment by Mygod** [comment]
@jeangb Meanwhile you can still use the workaround mentioned in the PR to get rid of the console output.

**Comment by jeangb** [comment]
Thank you @Mygod, in what class this workaround take place ?

**Comment by Mygod** [comment]
@jeangb Just whenever you create a `AppiumDriverLocalService`, do this on that object.

**Comment by jeangb** [comment]
@Mygod great, thx

**Comment by selenUser** [comment]
@Mygod which type is `streamField` ? (which import should I do ?)

**Comment by Mygod** [comment]
@selenUser

> `streamField = AppiumDriverLocalService.class.getDeclaredField("stream");`

It's a Field in reflection. :)

**Comment by drapostolos** [comment]
Perhaps this can be merged to master and released? To avoid workarounds...

**Comment by jeangb** [comment]
Do you think it would be possible to redirect this stream to an other view that console, in Eclipse. For example this view could be called Server.

**Comment by VenkateshPS** [comment]
Thanks @Mygod the workaround saved me.

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/java-client/pull/909

**Comment by Prasannajnaeyulu** [comment]
This is where one can find the workaround until the appium server with this changes is released
https://github.com/vector-im/riot-automated-tests/commit/73677dd38fa5228e99d58dff04844a70eaa31df7

**Pull request closed without merging**
