### PR TITLE
Add class chain locator type for iOS XCUITest-based driver

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Change list

Adds a new class chain locator type for iOS XCUITest-based driver
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

This PR is based on https://github.com/appium/appium-xcuitest-driver/pull/391
Class chain locator description and usage examples are present on https://github.com/facebook/WebDriverAgent/wiki/Queries

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I'd be very happy if one could provide me with xml source of the app we use for functional iOS testing, so I could add some tests for class chain locator type.

**Comment by SrinivasanTarget** [comment]
Interesting. @mykola-mokhnach TestApp is available in our repo, you can use the same and add some tests.

**Comment by mykola-mokhnach** [comment]
Done. Functional tests have been added

**Comment by SrinivasanTarget** [comment]
cool @mykola-mokhnach Will review in sometime

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget Are tests passed? I would like to publish it in BETA6.

**Comment by SrinivasanTarget** [comment]
Yes @TikhomirovSergey Its a merge away

**Comment by himankarbn** [comment]
@mykola-mokhnach @SrinivasanTarget:  Need some help... So far we have been using XCUITest for our automation. We recently started with Appium Ruby and would like to use `class_chain` locator type strategy but we are having some trouble with it. Here is a the sample tree of our login screen
screen shot 2017-09-06 at 10 12 14 am

In XCTest to get the Password text field we use `table.cells.containing(.staticText, identifier:"Password").children(matching: .secureTextField).element`

Is there a better/shorter way to find the password field using class_chain ? 
find_elements(:class_chain, 'XCUIElementTypeWindow/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeOther/XCUIElementTypeTable/XCUIElementTypeCell[3]/XCUIElementTypeStaticText')[0]

**Pull request merged**
