### PR TITLE
feat: Add wrappers for the Windows screen recorder

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Types of changes

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

Based on https://github.com/appium/appium-windows-driver/pull/66

### CODE REVIEW

**Comment by KazuCocoa** [comment]
CI is not happy?

**Comment by mykola-mokhnach** [comment]
@KazuCocoa This looks like integration test flakiness

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget Would it be possible to increase the maximum duration of the job on Azure CI?

**Comment by SrinivasanTarget** [comment]
> @SrinivasanTarget Would it be possible to increase the maximum duration of the job on Azure CI: [dev.azure.com/srinivasansekar/java-client/_build/results?buildId=358&view=results](https://dev.azure.com/srinivasansekar/java-client/_build/results?buildId=358&view=results) ?

Checking it @mykola-mokhnach

**Pull request merged**
