### PR TITLE
[XCUIT Mode] DoubleTap Support

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
## Change list

DoubleTap support to IOSTouchAction

## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

@rafael-chavez Apologies for the long delay. It is back in your authorship.

@TikhomirovSergey  FYI

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/java-client/pull/444

**Comment by SrinivasanTarget** [comment]
@rafael-chavez Can you please sign ```CLA```?

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget +1
@rafael-chavez Yes we need your sign

**Comment by rafael-chavez** [comment]
Signed @SrinivasanTarget @TikhomirovSergey

**Pull request merged**
