### PR TITLE
Upgrade to Gradle 5.4

### PR DESCRIPTION
**Pull request by valfirst**
## Change list

- Upgrade to Gradle 5.4
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [X] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
Lets fix scripts before merging this.

**Comment by mykola-mokhnach** [comment]
> ‌[simctl]‌ Error: Could not create simulator with name &#x27;appiumTest-DB957B92-4A87-4F5C-BD53-F60851B54D78-iPhone X&#x27;, device type id &#x27;iPhone X&#x27; and runtime id &#x27;11.4&#x27;. Reason: &#x27;simctl error running &#x27;create&#x27;: Invalid runtime: 11.4&#x27;‌

@SrinivasanTarget Can you please restart Azure jobs? There were several fixes in node-simctl to address such issues

**Comment by mykola-mokhnach** [comment]
We also need to switch Travis config to use x86 Android image like it was done in https://github.com/appium/appium-uiautomator2-driver/blob/master/.travis.yml

**Comment by mykola-mokhnach** [comment]
Closed because of https://github.com/appium/java-client/pull/1158

**Pull request closed without merging**
