### PR TITLE
chore: Bump Selenium version to 4.7.0

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
## Change list

Related to https://github.com/SeleniumHQ/selenium/issues/11347
 
## Types of changes

- [ ] No changes in production code.
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by SrinivasanTarget — APPROVED** [review]

**Review by valfirst — APPROVED** [review]

**Comment by nirtal85** [comment]
Hi team,  could you please merge this ASAP? we can't use Appium anymore - we must use the latest selenium because we do web-mobile combined tests that use CDP.

**Comment by valfirst** [comment]
It seems more changes are needed, the tests are failed:
```
        Caused by:
        org.openqa.selenium.WebDriverException: java.lang.NoSuchMethodException: org.openqa.selenium.remote.ProtocolHandshake.createSession(org.openqa.selenium.remote.http.HttpHandler, java.io.InputStream, long)
        Build info: version: '4.7.0', revision: '0a5b49d16f'
        System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '1.8.0_352'
        Driver info: driver.version: AndroidDriver
            at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:130)
            at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:102)
            at io.appium.java_client.remote.AppiumCommandExecutor.createSession(AppiumCommandExecutor.java:194)
            at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:262)
            at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:541)
            ... 7 more

            Caused by:
            java.lang.NoSuchMethodException: org.openqa.selenium.remote.ProtocolHandshake.createSession(org.openqa.selenium.remote.http.HttpHandler, java.io.InputStream, long)
                at java.lang.Class.getDeclaredMethod(Class.java:2130)
                at io.appium.java_client.remote.AppiumProtocolHandshake.createSession(AppiumProtocolHandshake.java:122)
                ... 11 more
```

The root cause is this change: https://github.com/SeleniumHQ/selenium/commit/558e0a0d3b23a97129f33c911192fc0ce72234b8.

**Comment by mykola-mokhnach** [comment]
Updated session creation

**Review by valfirst — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
@SrinivasanTarget Could you please release this changes in 8.3.0?

**Comment by SrinivasanTarget** [comment]
> @SrinivasanTarget Could you please release this changes in 8.3.0?

Sure

**Pull request merged**
