### PR TITLE
Jacoco plugin integration - Code Coverage

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
## Change list
1)Integrated jacoco plugin to enable code coverage post integration test run
2)Added Email ID 
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

##Details

Integrated jacoco code coverage plugin that generates reports post integration test run.
Doc:-  http://eclemma.org/jacoco/trunk/doc/maven.html

@TikhomirovSergey @Jonahss Please review it

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
https://github.com/appium/appium/issues/2448

**Comment by SrinivasanTarget** [comment]
@bootstraponline Your thoughts on this please?

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget 
I'm going to merge it soon. I like this PR

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget 
can you update plugin to the latesr version?
http://mvnrepository.com/artifact/org.jacoco/jacoco-maven-plugin

**Comment by bootstraponline** [comment]
> @bootstraponline Your thoughts on this please?

👍 I like jacoco.

**Comment by SrinivasanTarget** [comment]
Thanks @TikhomirovSergey @bootstraponline 

Resolved the merge conflicts and code looks good now.Please check.

**Comment by SrinivasanTarget** [comment]
https://github.com/codecov/example-java

**Comment by ronnelpinto** [comment]
@SrinivasanTarget, will this PR solve the issue of getting functional automation code coverage for Appium using Jacoco, asking because currently I am unable to get the functional code coverage of my app which is built using Gradle.

Thanks!

**Comment by SrinivasanTarget** [comment]
@ronnelpinto Yes, this give the functional coverage for java-client.

You can configure the same in gradle this way,

```
task jacocoTestReportDebug(type:JacocoReport) {
        group = "Reporting"
        classDirectories = fileTree(
                dir: 'build/intermediates/classes/debug',
                excludes: ['**/R.class',
                           '**/R$*.class',
                           '**/*$ViewInjector*.*',
                           '**/BuildConfig.*',
                           '**/Manifest*.*']
        )

        additionalSourceDirs = files(coverageSourceDirs)
        sourceDirectories = files(coverageSourceDirs)
        executionData = files('build/jacoco/testDebugUnitTest.exec')

        reports {
            xml.enabled = false
            html.enabled = true
        }
    }
```

**Comment by ronnelpinto** [comment]
Thanks for replying @SrinivasanTarget , I had a major issue trying to get the functional code coverage of my project once I moved it to Gradle. I have used Appium for functional automation. And had used Emma for code coverage back when the project was in Eclipse. 
Was just unable to make Appium and jacoco work. Hope this resolves my issue! Much thanks. 
I will keep following this PR and let you'll know for any further insights which i may have.

**Comment by SrinivasanTarget** [comment]
@ronnelpinto You're welcome

**Comment by TikhomirovSergey** [comment]
It is enough to run a single test and get some coverage info :)

>mvn install -Dtest=ServerBuilderTest

The result:



This is the great work!

**Comment by ronnelpinto** [comment]
@SrinivasanTarget @TikhomirovSergey,

Hi, needed help with a couple of things.
1.  Firstly how do I make my POM refer the latest change. I want to try the latest java-client code in my project to test this feature, but I guess the released version for java-client is 3.4.1. How do i make my POM refer this under development code to check?
2. Secondly, @SrinivasanTarget, I have added the JaCoCo dependency in my build.gradle file. I also have an Appium script which I need to run and get the code coverage. What are the other changes I need to do to the .apk or Appium script to make this change work. And where will I specify where to put the code coverage report post run. 

Much thanks for all the help!!

**Comment by ronnelpinto** [comment]
BTW, 
Here is the link to the Jacoco code coverage issue which i am facing from a long time now, just for visibility. I am assuming this PR fixes the issue: https://groups.google.com/forum/#!topic/jacoco/vx0g_6TKY8Q

**Comment by SrinivasanTarget** [comment]
@ronnelpinto As far as i understand from above question, Is it you wanted to get the code coverage of your app through Appium? If that is the case it is not possible to get code coverage of your/any app through appium.

Also please raise a question in appium discuss or https://github.com/appium/java-client/issues as it is difficult to answer in old PR's.

**Pull request merged**
