### PR TITLE
#356 Support for IntentAction and IntentCategory

### PR DESCRIPTION
**Pull request by saikrishna321**
## Change list

StartActivity with IntentAction and Category with optional params. 
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

StartActivityMethod with IntentAction and Category with optional params. I have added a sample IntentExample.apk.

@TikhomirovSergey @SrinivasanTarget Can you please review.

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
@saikrishna321 I like this PR.

Few minor remarks,
1.Code Styling: Please revert, https://github.com/saikrishna321/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L39 to individual imports statements.
2.Can we add ```appWaitPackage``` and  ```appWaitActivity``` also here https://github.com/saikrishna321/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L341 & https://github.com/saikrishna321/java-client/blob/master/src/main/java/io/appium/java_client/android/StartsActivity.java#L63. @TikhomirovSergey what do you say?
3.Also few comments to generate java doc's like this https://github.com/saikrishna321/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L318

Also i feel there are some minor fixes needs to be done on existing code: https://github.com/saikrishna321/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L327 
Can you pass over the ```appWaitPackage``` and  ```appWaitActivity```? By default we are passing null,it shouldn't be.

Tests looks fine. 👍 

@TikhomirovSergey Are you Ok with adding a new apk in repo? Please add on if any.

**Comment by TikhomirovSergey** [comment]
@saikrishna321 
It looks good in general. But there are some remarks.

Yes. @SrinivasanTarget  is rught. Please improve these issues. 

Also:
https://github.com/appium/java-client/pull/381/files#diff-2708c81d377c107c7d5d6819d8dc8bf2L285
I think this method should be declared by the _StartsActivity_ interface.

**Comment by saikrishna321** [comment]
@TikhomirovSergey @SrinivasanTarget have updated as per comments.. pls review

**Comment by SrinivasanTarget** [comment]
@saikrishna321 

Few more remarks,
1)Assert should be statically imported to have better readability: https://github.com/saikrishna321/java-client/blob/master/src/test/java/io/appium/java_client/android/IntentTest.java#L72
2)Doc should be updated here: https://github.com/saikrishna321/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L286 & https://github.com/saikrishna321/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L363
3)Don't think this is needed: https://github.com/saikrishna321/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L303 

On Existing code can you update the other needed parameters also here to look like other function calls we have:
https://github.com/saikrishna321/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L350

Please squash your commits post changes. 

@TikhomirovSergey Do you have anything to add on?

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget good catches :+1: 
I'm agree with @SrinivasanTarget's remarks except this point
> https://github.com/saikrishna321/java-client/blob/master/src/main/java/io/appium/java_client/android/AndroidDriver.java#L303

I think it is needed because **null** could be defined there. It may cause an error.

So some updates are needed still. @saikrishna321 When you'll finish and everything will be ok I'll merge this PR.

PS: The great contribution.

**Comment by SrinivasanTarget** [comment]
LGTM

**Comment by TikhomirovSergey** [comment]
I'm checking.

**Pull request merged**
