### PR TITLE
perf: Improve performance of proxy `Interceptor` logging

### PR DESCRIPTION
**Pull request by valfirst**
## Change list

Improve performance of proxy `Interceptor` logging
 
## Types of changes

What types of changes are you proposing/introducing to Java client?

- [ ] No changes in production code.
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by SrinivasanTarget — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
Could you please add some links to actual performance comparisons/documentation?

**Comment by valfirst** [comment]
That's a recommendation from SLF4J: https://www.slf4j.org/faq.html#logging_performance

**Comment by mykola-mokhnach** [comment]
> That's a recommendation from SLF4J: https://www.slf4j.org/faq.html#logging_performance

If I read it right the tutorial above advices something like `logger.debug("The new entry is {}.", entry);`

**Comment by valfirst** [comment]
> If I read it right the tutorial above advices something like logger.debug("The new entry is {}.", entry);

Right, that's a major improvement: replace `String.format` with parametrised message.

Also PR uses fluent logging approach (https://www.slf4j.org/manual.html#fluent), it allows to calculate logged values lazily (only if logging for the particular level is enabled).

**Pull request merged**
