### PR TITLE
Fixed doc issues in jdk 8

### PR DESCRIPTION
**Pull request by SrinivasanTarget**
## Change list

To skip doc issues on java 8 compiler
 
## Types of changes

What types of changes are you proposing/introducing to Java client?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Details

Added parameter to skip compilation issues related to doc on java 8 compiler.Also this is downward compatible.Works on both 7 & 8 compilers.

### CODE REVIEW

**Comment by SrinivasanTarget** [comment]
@TikhomirovSergey please review

**Comment by saikrishna321** [comment]
@SrinivasanTarget i do this locally to build. With this lint added, do you think we are stopping java doc creation for JDK 7 as well ?

**Comment by SrinivasanTarget** [comment]
We can solve this by creating a profile for java 8 and ignore doc but that's not the right way. So fixed this now.

Able to generate doc's on both jdk 7  & 8 now.

java 8 : https://gist.github.com/SrinivasanTarget/96454da9b9af507ca340a6797c1b03c5

java 7 : https://gist.github.com/SrinivasanTarget/c26fef3f8f017bb4d8a43a63564868c5

**Comment by TikhomirovSergey** [comment]
@SrinivasanTarget 
I think it was more correct to remove tags which are non supported by java 8. Please take a look at 
https://github.com/appium/java-client/commit/d8cd86d2149d861a6a7d423e9c0460518523163b

**Comment by SrinivasanTarget** [comment]
Cool Fixed in d8cd86d

Thanks @TikhomirovSergey

**Pull request closed without merging**
